### ISSUE TITLE
agreement_limit() fails with large datasets

### ISSUE THREAD

**Issue by IPolti** [arcaldwell49/SimplyAgree#52]
Hi!

When using the agreement_limit() function with a dataframe containing more than 3000 pairs of observations (3723 to be exact), I get the following error:
"Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
To enable adjustments, add the argument 'pbkrtest.limit = 3723' (or larger) [or, globally, 'set emm_options(pbkrtest.limit = 3723)' or larger]; but be warned that this may result in large computation time and memory use.
Note: D.f. calculations have been disabled because the number of observations exceeds 3000.
To enable adjustments, add the argument 'lmerTest.limit = 3723' (or larger) [or, globally, 'set emm_options(lmerTest.limit = 3723)' or larger]; but be warned that this may result in large computation time and memory use.
Error in `select()`:
! Can't subset columns that don't exist.
✖ Column `lower.CL` doesn't exist."

Could this problem be avoided if an argument is included in agreement_limit() to adjust lmerTest when using large datasets?

Best,

**Comment by arcaldwell49** [comment]
Yeah, let me think about the best approach

**Comment by arcaldwell49** [comment]
Two things: 

1) a branch has been created to address this issue entitled "df_lmer_limit". You can pull from that to get a tentatively working function. It may be a little time before I merge with the main branch.

2) The tolerance_limit function does not have this issue.
