### ISSUE TITLE
mac-specific files in repo

### ISSUE THREAD

**Issue by slwu89** [arcaldwell49/SimplyAgree#8]
Hi @arcaldwell49, 

I noticed there is a .DS_Store file lurking in the repo, I'd suggest adding the MacOS .gitignore to the project's .gitignore so files like this can be filtered out https://github.com/github/gitignore/blob/main/Global/macOS.gitignore 

I don't consider this  blocking for acceptance/review, just a suggestion.

**Comment by arcaldwell49** [comment]
@slwu89 very good catch and something I noticed just yesterday. Removed and added to the gitignore
