### ISSUE TITLE
vignette/docs comments

### ISSUE THREAD

**Issue by slwu89** [arcaldwell49/SimplyAgree#9]
1. In line https://github.com/arcaldwell49/SimplyAgree/blob/9aeb034a7b3dbfaefa6ef69e154dba9360b51880/vignettes/intro_vignette.Rmd#L71 \gamma_{1-\alpha} is not surrounded by `$` so it does not render on the docs site.
2. I suggest adding a link to the docs website (https://aaroncaldwell.us/SimplyAgree/index.html) somewhere to the repo main page since some users won't read the JOSS paper to find it, either on the README.md or in the sidebar "About" to the right, under "website". It can also be added to the `URL` field of the DESCRIPTION (https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file)

**Comment by arcaldwell49** [comment]
Just pushed an update in the branch I am working on where the website is linked to in the README. Just as a note, the URL is already in URL field of the DESCRIPTION file.

Undergoing checks now and should be merged with the main branch today.

**Comment by slwu89** [comment]
Ok, thanks, I missed that.

**Comment by arcaldwell49** [comment]
No worries, the comments have been really helpful.  Keep them coming!

**Comment by slwu89** [comment]
closed with https://github.com/arcaldwell49/SimplyAgree/pull/12
